apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hkm234505-go 
  janus-idp.io/tekton: hkm234505-go
  backstage.io/kubernetes-id: hkm234505-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hkm234505-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml