apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hkm234505-go
  janus-idp.io/tekton: hkm234505-go
  backstage.io/kubernetes-id: hkm234505-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hkm234505-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
